### PR TITLE
Merge 6.9.2

### PR DESCRIPTION
**Pull request by ouuan**

### CODE REVIEW

**Review by neko-para — APPROVED** [review]

**Comment by ouuan** [comment]
> [ouuan](/ouuan) requested review from [cpeditor/maintainers](/orgs/cpeditor/teams/maintainers), [coder3101](/coder3101), [neko-para](/neko-para) and [swift-zym](/swift-zym) and removed request for [cpeditor/maintainers](/orgs/cpeditor/teams/maintainers) [2小时前](#event-4925888310)

https://github.com/cpeditor/cpeditor/pull/858#event-4913422996 also looks like this. I think this request-and-remove is a GitHub bug. I guess this happens when the person who requests the review is also in the requested team.

**Comment by ouuan** [comment]
> [#858 (comment)](https://github.com/cpeditor/cpeditor/pull/858#event-4913422996) also looks like this thinking I think this request-and-remove is a GitHub bug. I guess this happens when the person who requests the review is also in the requested team.

I want to make a test here, sorry if this sends notifications to others' in-boxes.

**Comment by ouuan** [comment]
OK, it seems that this is not a bug :thinking: Maybe I did some wrong operations when I created this PR.

**Comment by ouuan** [comment]
> requested review from [cpeditor/maintainers](/orgs/cpeditor/teams/maintainers), [coder3101](/coder3101) and [swift-zym](/swift-zym) and removed request for [cpeditor/maintainers](/orgs/cpeditor/teams/maintainers) [15秒钟前](#event-4926295557)

It appears again when I didn't mean to make a test...

**Comment by ouuan** [comment]
It's weird :thinking: This bug only happens for "cpeditor/maintainers", but not for "cpeditor/zh-cn-translators".

**Review by coder3101 — APPROVED** [review]

**Comment by coder3101** [comment]
> > [#858 (comment)](https://github.com/cpeditor/cpeditor/pull/858#event-4913422996) also looks like this thinking I think this request-and-remove is a GitHub bug. I guess this happens when the person who requests the review is also in the requested team.
> 
> I want to make a test here, sorry if this sends notifications to others' in-boxes. Hope everyone is receiving emails grouped in a single dialog instead of multiple entries 🙏

Strange, I did not get any email for reviews

**Pull request merged**
