### PR TITLE
The Chinese part of READMEs

### PR DESCRIPTION
**Pull request by neko-para**
Still work in progress.

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [ ] New feature (changes which add functionality)
- [x] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [ ] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [ ] The settings file in the old version can be used in the new version after this change.
- [ ] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [ ] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [ ] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [ ] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by coder3101** [comment]
Why isn't this merged? Only after this is merged, @sadykhzadeh can work on Russian translation.

**Comment by ouuan** [comment]
> Why isn't this merged?

Because I think the README of Settings is not good enough, but I have no time to improve it.

However, it's not bad, you can approve and merge it, and we can improve it later.

**Comment by ouuan** [comment]
And we should start migrating the documents to the website, where we can make the documents more organized and more detailed. So it's better to stop translating the old documents now.

**Comment by coder3101** [comment]
> And we should start migrating the documents to the website, where we can make the documents more organized and more detailed. So it's better to stop translating the old documents now.

Don't we need Russian translation of these doc's? Improving or updating a translation is easier than translating from scratch. Let him work on translating this time and we can then migrate to website.

I think /doc will move to website repository. But these src/Core/readme_xx-XX should remain in source for help to developers

**Comment by ouuan** [comment]
> Don't we need Russian translation of these doc's? Improving or updating a translation is easier than translating from scratch. Let him work on translating this time and we can then migrate to website.

We don't simply move things like MANUAL.md and INSTALL.md to the website, we'll restructure them.

We can simply split INSTALL.md into several parts, but the current manual is in a mess and is incomplete, it's only separate tips, we have to rewrite it.

> I think /doc will move to website repository. But these src/Core/readme_xx-XX should remain in source for help to developers

Other READMEs are good to keep in the src directories, but the long introduction to the settings system can be moved to the website.

**Pull request merged**
