### PR TITLE
feat: Gracefully exit on Signals 

### PR DESCRIPTION
**Pull request by coder3101**
## Description
Adds Signal handler with help of QCtrlControl 

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [x] New feature (changes which add functionality)
- [ ] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by coder3101** [comment]
I have left the handing signal with a comment on what should be expected behaviour or what could be better than this as per your wish. I have ported the changes to appwindow and other helper API from #268 into this.

I also confirm that now, I am able to exit gracefully (with hot exit enabled) and that this library works fine on my windows.

**Comment by ouuan** [comment]
Now it doesn't catch SIGHUP, which is sent on Linux when closing the terminal where the application was started :thinking:. However, I saw SIGHUP in `qctrlsignalhandler_unix.cpp`, we may need to find out how to catch it later.

And, without this:

https://github.com/cpeditor/cpeditor/blob/68140a7903b700b443063a721a5e1e5ae3bc2edd/src/Application.cpp#L255

, the application won't be killed after receiving SIGTERM during the progress dialog.

**Comment by ouuan** [comment]
Please test the latest commit first.

**Comment by coder3101** [comment]
> Please test the latest commit first.

It still works on my Windows but when Hotexit is not enabled `SIGINT` opens the dialog box to ask for saving changes, and same with killing from task manager.

If it will pop open the `closeConfirm` dialog what good it is? I thought application would exit normally and in next launch show a dialog "Unexpected close, want to restart?"

**I have not still ran this commit, will confirm this behaviour in 5-6 hours, I tested locally by putting exact code as you have for signal handling now, (copy pasted old handling code) and found this behaviour**

**Comment by ouuan** [comment]
> If it will pop open the `closeConfirm` dialog what good it is? I thought application would exit normally and in next launch show a dialog "Unexpected close, want to restart?"

I think this is useful on Linux. SIGINT is the same as a normal close, so the user can use Ctrl+C to normally close it. It is strange that the dialog is also showed when it's killed from the Windows task manager, maybe we can treat SIGINT as SIGTERM on Windows.

**Comment by ouuan** [comment]
I just noticed that d5ea61ba4d6c5fe553c32d877ea1de14529883b2 has been not working since the new preferences window, because now the settings are saved when normally exiting. After this PR is finished and merged, the feature introduced by that commit will be more useless, so instead of making it work again, we can simply remove it.

**Comment by coder3101** [comment]
What behaviour you want when SIGTERM and SIGINT is invoked in Windows( from git bash)? I will try to fix it tell me behaviour with Hotexit and without Hotexit?

> Note that killing from Task manager sends SIGINT

You work on behaviour for UNIX.

**Pull request closed without merging**
