### PR TITLE
feat: update icon for macOS

### LINKED ISSUE #834: Update icon for macOS
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Make the icon follow [Apple's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by swift-zym**
## Description

Update icon for macOS.

## Related Issues / Pull Requests

Closes #834 

## Motivation and Context

Make the icon follow [Apple's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).
## Screenshots (if appropriate)

macos-icon

## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [x] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by coder3101** [comment]
This icon sure looks more consistent with macOS and apple design, the question is, should we have different icon for different OS? What is your opinion @ouuan on this?

**Comment by ouuan** [comment]
The app icon in the Dock looks good, but do we need to change the in-app icon (which is displayed on the home page of the preferences window and some other places)? @swift-zym What do you think?

**Comment by coder3101** [comment]
> The app icon in the Dock looks good, but do we need to change the in-app icon (which is displayed on the home page of the preferences window and some other places)? @swift-zym What do you think?

In my opinion changing launcher icon is enough. This will also remove those conditional OS macros from code which makes it looks like we have different icon for different OS.

Please share your opinion @swift-zym ?

**Comment by swift-zym** [comment]
@coder3101  @ouuan  I agree that we needn't change the in-app icon,but I think we should keep the code in `appwindow.cpp` and `main.cpp`, it will change the dock icon when running.

**Review by ouuan — APPROVED** [review]
LGTM, thanks!

**Comment by ouuan** [comment]
@allcontributors add @swift-zym as a contributor for code and design.

**Review by coder3101 — APPROVED** [review]

**Comment by coder3101** [comment]
Does the old icon not at all used by macOS now?

**Comment by ouuan** [comment]
> Does the old icon not at all used by macOS now?

5fb109e71013d31b33827fa06467084d2d4814e3

**Pull request merged**
