### PR TITLE
feat: watch checker source file

### LINKED ISSUE #843: Support update/remove custom checkers
**Is your feature request related to a problem? Please describe.**

Now cpeditor doesn't auto re-compile custom checker when checker's source file changed.

**Describe the solution you'd like**

Provide "Update" and "Delete" buttons next to "Add Checker".

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by swift-zym**
## Description

Ask whether to re-compile current checker when it changed.
## Related Issues / Pull Requests

Fixes #843 
## How Has This Been Tested?

macOS 12.0
## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [x] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by ouuan** [comment]
Do we need a prompt and an option? I think a silent recompilation could be the only behavior :thinking:

**Comment by swift-zym** [comment]
> Do we need a prompt and an option? I think we can silently recompile and don't need an option 🤔

I think this will cause the checker can't be use if the source file is deleted

**Comment by ouuan** [comment]
> I think this will cause the checker can't be use if the source file is deleted

Then just don't recompile when it's deleted.

**Comment by ouuan** [comment]
I think it's not very good to recompile on file changes, whether prompted or not, if you are editing and saving the checker.

**Comment by ouuan** [comment]
Maybe we should check this on execution.

**Pull request closed without merging**
