### PR TITLE
build(aur): use Ninja to build

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Use Ninja to build in the PKBUILD for AUR.

## Motivation and Context

1. Ninja doesn't spam in the terminal like `make`.
2. It is a little bit faster.

## How Has This Been Tested?

Used `makepkg -si` to install the PKGBUILD.

### CODE REVIEW

**Comment by ouuan** [comment]
I'm wondering whether always color by default could cause some problems, like when building in the IDE :thinking: However, I always build in the terminal so I can't test.

**Comment by ouuan** [comment]
Maybe it's a better choice to disable always color by default and enable it in the PKBUILD.

**Comment by ouuan** [comment]
But if always color wouldn't cause problem unless you redirect the output to a file, it's good to enable it by default so that people using Ninja don't have to enable it manually.

**Comment by coder3101** [comment]
I don't think color is that big of a deal. Let's not worry about Build steps. We should keep it default as offered by CMAKE.

**Comment by ouuan** [comment]
> I don't think color is that big of a deal.

If it shows color in unsupported place, the output will be in a mess.

> Let's not worry about Build steps.
> We should keep it default as offered by CMAKE.

These are somehow conflicted, because the default now is not the default offered by CMake. What do you mean by "not worry"?

**Pull request merged**
