### PR TITLE
feat: use KSyntaxHighlighter for code highlighting

### PR DESCRIPTION
**Pull request by rogeryoungh**
Use Kate's Syntax highlighter engine for Code Highlighting.

## Description

This PR is the same as #516, but without FakeVim.

## Related Issues / Pull Requests

#516

## Motivation and Context

To make syntax highlighting more better.

## How Has This Been Tested?

Tested on Arch Linux.

## Screenshots (if appropriate)

github looks broken
github looks broken

## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [x] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by ouuan** [comment]
> My guess is that `window-latest` points to Windows Server 2022 and VS 2022, but `2019` is hardcoded in many places in the build process.

You may try updating it. It would be preferred if the VS version can be not hardcoded while not adding too much complexity in the scripts.

> Ubuntu may also can be updated to 20.04 or 22.04.

linuxdeployqt recommends targeting the oldest still-supported Ubuntu LTS release, which is still 18.04.

**Comment by coder3101** [comment]
There are functions like `isPositionInsidexxxx` in CodeEditor.cpp which was incomplete in original PR. 

The main goal of those function was that when highlighting matching parenthesis we will ignore the parenthesis that comes inside comments, single/double quotes or string literals. 

Its incomplete here as well.

**Comment by rogeryoungh** [comment]
I'm trying to use [KTextEditor](https://api.kde.org/frameworks/ktexteditor/html/index.html).

Currently, basic editing and highlighting work fine. It looks like Kate is studded.

image

**Comment by coder3101** [comment]
KTextEditor is nice, If we are able to compile on all platforms. Back in the days, it was not fully cross platform. Now it seems a good choice for us.

**Comment by rogeryoungh** [comment]
I recently tried KTextEditor again, referred some code to Kate, and now I can highlight the error line, the text hint is not yet completed, and I guess it will be solved smoothly.

github looks broken



But I'm running into some sticky issues.

- KTextEditor is bound to some shortcut keys, such as Ctrl+S, Ctrl+F, etc., which cause conflicts with the main window.
- KTextEditor has its own Cursor, and it is difficult to convert with QTextCursor, which breaks many functions.
- KTextEditor provides three setting methods, and serialization encountered difficulties.
   1. [ConfigInterface](https://api.kde.org/frameworks/ktexteditor/html/classKTextEditor_1_1View.html#view_config), less options.
   2. [Editor Config](https://api.kde.org/frameworks/ktexteditor/html/classKTextEditor_1_1Editor.html#editor_config), this component can be embedded in Dialog or Widget. The UI is a bit inconsistent, the language doesn't follow the settings, and Reset doesn't seem to be able to roll back some options.
   3. [writeSessionConfig](https://api.kde.org/frameworks/ktexteditor/html/classKTextEditor_1_1View.html#a9aea3e3a3200c251d2a7fbbca342cae3), I haven't tried it, it may be the same as 1 or 2.



To use KTextEditor, we need a massive redesign.

**Comment by rogeryoungh** [comment]
I fixed the bracket matching code. Refer to the code of [Kate](https://github.com/KDE/ktexteditor/blob/kf5/src/syntax/katehighlight.cpp#L173) to maintain the Attribute of each row in the highlighter. Now we can directly get the style at a certain position to judge whether it is in the string or comment. So `isPositionInsidexxxx` is no longer needed.

https://github.com/rogeryoungh/cpeditor/blob/ksyntax-highlighting2/src/Editor/CodeEditor.cpp#L736-L754

QtFindReplaceDialog waits for https://github.com/cpeditor/QtFindReplaceDialog/pull/9.

**Comment by coder3101** [comment]
I have reviewed the code, and next will test it. Thanks for all your efforts! 😃

**Review by coder3101 — APPROVED** [review]
Looks good!
Could you please run the release script in your fork and share the release artifact. We could test if all required dependencies are getting bundled

**Comment by coder3101** [comment]
Got it [here](https://github.com/rogeryoungh/cpeditor/releases/tag/7.0.0

**Comment by coder3101** [comment]
@ouuan can you test on Linux?
Works fine on macOS and Windows.

**Comment by ouuan** [comment]
It generally works. But see the unchecked items in #516. There are some regressions, though not very critical.

**Comment by coder3101** [comment]
Minor regression is fine, we can iron it out slowly in subsequent PR, as for small unfulfilling requirements, we can list it out in a single issue and fix it.

What do you think @rogeryoungh?

**Comment by rogeryoungh** [comment]
I agree with you.

I found a small problem during the test, the color of the error lines and the current line does not mix well, and it cannot be seen under some themes, I will fix it right away.

**Review by coder3101 — APPROVED** [review]

**Comment by coder3101** [comment]
We can merge this and let alpha version users find and report bugs or regression.

Hope @rogeryoungh will contribute in fixing and triaging them.

**Comment by ouuan** [comment]
@allcontributors add @rogeryoungh for code

**Comment by ouuan** [comment]
@all-contributors add @rogeryoungh for code.

**Pull request merged**
