### PR TITLE
feat(UpdateChecker): add proxy support

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Now you can use proxy to check for updates.

## Motivation and Context

In some countries, it's easier to check for updates via proxy.

## How Has This Been Tested?

On Arch Linux, with clash and both Http and Socks5 proxy.

### CODE REVIEW

**Comment by StudyingFather** [comment]
Maybe we can add a option to disable proxy (direct connection).

That is, we have three options:

- disable proxy
- use system setting
- enable proxy

**Comment by ouuan** [comment]
During the test on Windows, I found that we missed the OpenSSL DLLs in the installer, and the update checker always has the error "TLS initialization failed". I thought that's because of my internet connection before, till today I used the proxy and it still has this error.

**Comment by ouuan** [comment]
> During the test on Windows, I found that we missed the OpenSSL DLLs in the installer, and the update checker always has the error "TLS initialization failed". I thought that's because of my internet connection before, till today I used the proxy and it still has this error.

It also happens on the AppImage. So maybe the users were never able to check for updates in the application.

**Comment by neko-para** [comment]
> > During the test on Windows, I found that we missed the OpenSSL DLLs in the installer, and the update checker always has the error "TLS initialization failed". I thought that's because of my internet connection before, till today I used the proxy and it still has this error.
> 
> It also happens on the AppImage. So maybe the users were never able to check for updates in the application.

You can install openssl in Qt Installer, and the dlls are under $QTROOT/Tools/OpenSSL/$platform/bin

**Comment by neko-para** [comment]
If the dlls are in the same directory of cpeditor, the error disappear.

**Comment by ouuan** [comment]
> You can install openssl in Qt Installer, and the dlls are under $QTROOT/Tools/OpenSSL/$platform/bin

> If the dlls are in the same directory of cpeditor, the error disappear.

Please discuss OpenSSL related things in #449 and #451.

**Comment by coder3101** [comment]
You should merge this PR after his approval.

**Comment by neko-para** [comment]
Sorry, I'm outside yesterday. I'll test it right now.

**Comment by neko-para** [comment]
I works fine on my machine. I test right proxy and wrong proxy and cpeditor works fine.

**Pull request merged**
