### PR TITLE
ci(check_format): Auto create PR to fix format

### PR DESCRIPTION
**Pull request by ouuan**
##  Description

Auto create PR for Clang Format check.

## Motivation and Context

In this way, we can fix wrong format more easily.

This is better than commit directly, because:

1. It works on protected branches.
2. We can choose to merge it or change it manually.
3. After the merge, CI will run on it. Though it won't before the merge, we can still revert/fix it easily after the merge.

## Type of changes

- [x] CI (changes to CI configuration files and scripts)

### CODE REVIEW

**Comment by coder3101** [comment]
Does it creates PR for PR that fails code formatting? I don't see a restriction to run this only on `push`

**Comment by ouuan** [comment]
> Does it creates PR for PR that fails code formatting? I don't see a restriction to run this only on `push`

Pull requests can't use secrets, so it will fail to open a PR when it's triggered by a PR.

See #250 and [the check run](https://github.com/cpeditor/cpeditor/pull/250/checks?check_run_id=612914390).

**Comment by coder3101** [comment]
So now CI will fail if a typo is in PR or its code format is not as per our styles. As with code format the PR proposer can know that he/she needs to run clang format. As for spell fixer, how will they know where is the spelling mistake?

**Comment by ouuan** [comment]
> As for spell fixer, how will they know where is the spelling mistake?

1. They can enable GitHub Actions in their forks, and possibly re-push.
2. They can read the diff in the check run.

**Pull request merged**
