### PR TITLE
feat(Appearence): Allow non monospaced font in FontDialog

### LINKED ISSUE #217: Toggle "view all fonts" when choosing font
**Is your feature request related to a problem? Please describe.**

Some monospace fonts don't display when `QFontDialog::MonospacedFonts` is set. It's reported that PragmataPro is one of them.

**Describe the solution you'd like**

Add a "view all fonts" option in the settings.

Since there are more and more font settings, it's good to split Appearance into Appearance/Fonts and Appearance/Miscs.

**Additional context**

It seems that QFontDialog doesn't support this or I didn't find it, so I don't know how to implement this up to now.

### PR DESCRIPTION
**Pull request by coder3101**
Some coding fonts are non monospaced like FiraCode on some platform and Powerline fonts are also non-monospaced. Previously user can only set fonts which were monospace. In this PR we add a checkbox that can stop the monospace font filtering and user can set up any font as Editor/Testcase/MessageLogger/Application font.

## Description
Add a new Setting to Preference/Appearance and override `areSettingsChanged()`

## Related Issue
Fixes #217 

## Motivation and Context
To give user more flexibility.

## How Has This Been Tested?
Arch Linux with KDE

## Screenshots (if appropriate)
image

## Type of changes

- [x] New feature (changes which add functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] If there are changes of the text displayed in the UI, I have wrapped them in `tr()` or `QCoreApplication::translate()`.
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by coder3101** [comment]
@ouuan  and @IZOBRETATEL777 or @sadykhzadeh translation needed.

**Comment by coder3101** [comment]
Opened documentation PR at https://github.com/cpeditor/cpeditor.github.io/pull/75

**Comment by coder3101** [comment]
@ouuan You can review and merge this PR and the corresponding PR in documenation

**Comment by ouuan** [comment]
Why do you update qhttp in this PR?

**Comment by coder3101** [comment]
> Why do you update qhttp in this PR?

You can revert, approve and merge! I might have forgot the branch before I pushed it.

**Review by ouuan — APPROVED** [review]

**Pull request merged**
