### PR TITLE
Add all contributors

### PR DESCRIPTION
**Pull request by ouuan**
Manually resolve conflicts for #291, #292, #293, #294, #295, #296, #297, #298, #299, #300, #301, #302, #303, #304, #305, #306, #307, #308, #309, #310, #311, #312, #313, #314.

### CODE REVIEW

**Comment by ouuan** [comment]
@allcontributors add @ouuan for code.

**Comment by ouuan** [comment]
@allcontributors add @ouuan for code.

**Comment by ouuan** [comment]
@allcontributors add @ouuan for code.

**Comment by coder3101** [comment]
Why is codacy review pending? Can you manually trigger it?

**Pull request merged**
