### PR TITLE
docs(DONORS): move "DONATORS.md" to "DONORS.md"

### PR DESCRIPTION
**Pull request by ouuan**
"donators" is not listed in Oxford Advanced Learner's Dictionary.

Also: https://www.quora.com/Whats-the-difference-between-donor-and-donator

### CODE REVIEW

**Comment by coder3101** [comment]
So have you checked and if applicable refactored inside application as well?

**Comment by ouuan** [comment]
> So have you checked and if applicable refactored inside application as well?

The application displays DONATE.md.

**Comment by coder3101** [comment]
> > So have you checked and if applicable refactored inside application as well?
> 
> The application displays DONATE.md.

Fine, Just wanted to confirm.

**Review by coder3101 — APPROVED** [review]

**Comment by ouuan** [comment]
Actually, the donor list is not displayed anywhere in the application. It only displays DONATE.md.

**Comment by coder3101** [comment]
> Actually, the donor list is not displayed anywhere in the application. It only displays DONATE.md.

I actually meant if inside application we showed or used the word "Donators", so we should change it to "Donors".

**Pull request merged**
