### PR TITLE
feat: add 'save to file' in the context menu of the test cases

### LINKED ISSUE #529: Add "save to file" in the context menu of the test cases
**Is your feature request related to a problem? Please describe.**

Some contests require the answer file instead of the source file. So it will be good if the output can be saved to a file.

**Describe the solution you'd like**

Add "save to file" in the context menu of the test cases.

**Describe alternatives you've considered**

1.  Let the user generate the output file outside of CP Editor.
2.  Make it possible to set file paths for test cases. But that's not easy to implement.

### PR DESCRIPTION
**Pull request by ChungZH**
## Description

Add "save to file" in the context menu of the test cases.

## Related Issue

close #529

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [x] New feature (changes which add functionality)
- [ ] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] If there are changes of the text displayed in the UI, I have wrapped them in `tr()` or `QCoreApplication::translate()`.
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ChungZH** [comment]
> 1. Please use `Util::saveFile` in `src/Util/FileUtil`.
> 2. There are some unnecessary white space changes, probably because your format setting was wrong.
> 3. I think "save to file" can be useful for input and expected, too?

Fixed~

**Comment by coder3101** [comment]
Great. One final thing:
- If you are using Linux please run `tools/updateTranslations.sh` from the root of the project. It will fix CI and modify the translation files. Optionally if you know the Chinese language you can add a translation for Chinese and likewise use Google translate for Russian 

Optionally @ouuan can you modify the CI to open a PR to update translation files?

**Comment by ouuan** [comment]
> Optionally @ouuan can you modify the CI to open a PR to update translation files?

I didn't add that because we should not only run `updateTranslations.sh` but also update the translations. Sometimes we don't update the translations on purpose, for example, to keep the old translations because the source text is changed but the old translations are still useful. In short, an automated PR to update the translations is often useless.

**Comment by coder3101** [comment]
@all-contributors add @ChungZH for Code

**Pull request merged**
