### PR TITLE
(WIP) Add C++ debugging support

### LINKED ISSUE #17: Add GDB support
**Is your feature request related to a problem? Please describe.**

I don't know how to use GDB with CP Editor.

**Describe the solution you'd like**

Support GDB with GUI, like many other IDEs.

**Describe alternatives you've considered**

Support GDB in command line.

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by neko-para**
## Description

Use gdb, gdbserver in path to debug c++ program. Add a simple dialog for debug control.
Add a new library [qgdbint](https://github.com/neko-para/qgdbint).
Still work in progress.

## Related Issue

This closes #17.

## How Has This Been Tested?

write simple program and check whether debug feature works well(including Excution, Breakpoints.)

* Ubuntu 18.04 x64(on WSL), gdb 8.1
* Windows/MSYS2 x64, gdb 9.0

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [x] New feature (changes which add functionality)
- [ ] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [ ] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [ ] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ouuan** [comment]
Did you use new features in Qt 5.14?

**Comment by neko-para** [comment]
I use Qt::SkipEmptyParts, which was introduced in Qt 5.14. I'll fix this in the next commit.

**Comment by ouuan** [comment]
BTW, you can [enable GitHub Actions in your fork](https://github.com/neko-para/cpeditor/actions), then your codes will be automatically formatted. When you are finished, I can squash and merge, and the format commits will be squashed into a single commit, which is better than merge into master and then another format commit.

**Comment by neko-para** [comment]
I'll do it later.
Is it possible to change the old settings' type? I'd like to change the type of runtime arguments from string to stringlist, but this may cause some compability issue. Or it's ok to try to parse the string to strnglist, which only influence the debug(I use stringlist as arguments when excuting gdb)

**Comment by neko-para** [comment]
I've just found that it's easy to install clang format 9 on ubuntu(I used to think that only old versions are in the repository). I'll do the formatting locally.

**Comment by ouuan** [comment]
Are there any problems with the current implementation? I guess it's OK to use the runtime arguments (a QString) as an element of a  QStringList, or use QString in `QGdbProcessManager::prepare`.

**Comment by neko-para** [comment]
This will combine all arguments into one, which is not what it should be.
For example, we supposed to run
./test arg1 arg2
In the current implementation, it works like
./test "arg1 arg2"
It may cause unknown problems(this won't happen in normal run. It only appear when debugging)

**Comment by ouuan** [comment]
What about using QString in `QGdbProcessManager::prepare`?

**Comment by neko-para** [comment]
It has the same problem.
Maybe i can use ```void QProcess::start(const QString &command, QIODevice::OpenMode mode = ReadWrite)``` instead of ```void QProcess::setArguments(const QStringList &arguments)```.
I'll try it later.

**Comment by neko-para** [comment]
I've do some tests.
I use the start(cmd), and it doesn't work as expected.
when I run
./test arg1 "arg 2"
which means set arguments to ```arg1 "arg 2"``` and ./test will print argc
'run' will print 3 and 'debug' will print 4(which means the second argument is divided into two part)
But when i set argument to ```arg1 "arg\ 2"```, 'debug' print 3.
Maybe I should manually divide the argument string

**Comment by coder3101** [comment]
> Or it's ok to try to parse the string to strnglist.

This is a better approach, Neither our QString will be affected nor Any settings changes are required. Make sure to chop them correctly handling "(quotes) and other special characters. 

Like,

```cpp
$ ./capitalizer "capitalize this" --upto 5
$ CAPITalize this
```

It has only 3 arguments. In settings, we will make sure that user adds a `" "` or `' '` for space-separated commands. This also makes sense, doesn't it? You would split it into QStringList as `{capitalize this, --upto, 5}` and use for your purpose.

BTW, Your code looks Okay to me, Just format it (optionally), and Make sure that You keep our source compilable on at least 5.12

Thanks for your contribution.

**Comment by neko-para** [comment]
I write a function in Util and it works well. I'll also change the Runner to use the splitted arguments.

**Comment by neko-para** [comment]
But i'm not sure the run_xxx settings should always be a program or could contain some option. If it contains options, I shall parse it too.

**Comment by ouuan** [comment]
> But i'm not sure the run_xxx settings should always be a program or could contain some option. If it contains options, I shall parse it too.

I think options should be in the runtime arguments :thinking:

**Comment by neko-para** [comment]
So the run command should always be a path to program? If the run command contains options like ```java -xxx```(I know few about java), I can parse it.

**Comment by ouuan** [comment]
Is there any case that the options must be in the run command not in the runtime arguments?

**Comment by neko-para** [comment]
I don't know. Actually when someone needs this feature, he should change the IDE

**Comment by ouuan** [comment]
> I don't know. Actually when someone needs this feature, he should change the IDE

In fact, I don't know how runtime arguments are useful in Competitive Programming.

**Comment by neko-para** [comment]
```
$ python --help
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
...
```
according the usage, I think there are many options should be placed before the file

**Comment by neko-para** [comment]
yep. It is not so important

**Comment by ouuan** [comment]
However, perhaps it's still good to make it able for users to add options both at the beginning (run command) and at the end (runtime arguments).

**Comment by neko-para** [comment]
But this feature may cause compability problem.
In the old(and now) setting file, the program path in run command is not quoted, and if some users specify the path of java(like C:\java\bin\java.exe) instead of adding it to path, it will cause an error.

**Comment by ouuan** [comment]
> But this feature may cause compability problem.
> In the old(and now) setting file, the program path in run command is not quoted, and if some users specify the path of java(like C:\java\bin\java.exe) instead of adding it to path, it will cause an error.

Then it's better not to change. We can wait until someone requests for this feature.

**Comment by coder3101** [comment]
I was thinking how will user add breakpoint? Does QCodeEditor has it now?

**Comment by ouuan** [comment]
> BTW, Your code looks Okay to me

> I was thinking how will user add breakpoint? Does QCodeEditor has it now?

So you approved these changes without trying it?

**Comment by neko-para** [comment]
> I was thinking how will user add breakpoint? Does QCodeEditor has it now?

QCodeEditor doesn't suppot marks on the left margin. Currently the 'add' button will add a breakpoint according to the cursor. It needs changed, but now it's just for test. Meanwhile, the cursor in the editor will automatically change according to the current line(when running)

**Comment by ouuan** [comment]
It often crashes when I press "start" in the debug window on my machine :thinking: 

Is this still work in progress? Next time you can open a draft PR for work in progress.

**Comment by coder3101** [comment]
> > BTW, Your code looks Okay to me
> 
> > I was thinking how will user add breakpoint? Does QCodeEditor has it now?
> 
> So you approved these changes without trying it?

No I just meant that code quality and how it is organised looks good. Before merging we will try it for sure!

**Comment by coder3101** [comment]
@neko-para are you waiting on some other feature before this can be implemented? It has been quite a long time since we got any activity here!

**Comment by neko-para** [comment]
Yes, I've working on the new preferences window before.
I still don't know how to highlight a certain line(to show breakpoints and the current running row).
I'll restart updating it soon, but I need some features of QCodeEditor.

**Comment by neko-para** [comment]
Maybe i can move the branch from my fork to this repository?

**Comment by neko-para** [comment]
But it is a big job to make that old branch to fit the new code structure.

**Comment by neko-para** [comment]
All codes will be moved to a local branch from the forked one.

**Comment by neko-para** [comment]
Move to [340](https://github.com/cpeditor/cpeditor/pull/340)

**Pull request closed without merging**
