### PR TITLE
 feat: add Spanish translations

### LINKED ISSUE #1130: Spanish translation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

_No response_

### Describe the feature you'd like

I would like to help by adding a Spanish translation. I want to start with the application texts, then website and docs. I'm new to qt, so might need a bit of help setting up the .ts file.

### Describe alternatives you've considered

_No response_

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by D4NZ-jpg**
## Description

Added Spanish translations, and the files required for it

## Related Issues / Pull Requests

This closes #1130 

## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [ ] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by ouuan** [comment]
Looks good to me. You can ask some friends to review it or I can also merge it right now.

**Comment by coder3101** [comment]
> Looks good to me. You can ask some friends to review it or I can also merge it right now.

I think we can merge it, improvements can be done later by other Spanish users.

**Comment by D4NZ-jpg** [comment]
A friend has already partially reviewed the translations, but in the future, I would like to ask a few more friends to check it more thoroughly. This may take some time, but I think it is ready to be merged for now, and as @coder3101 said, improvements could also be done by other users later on.

**Review by ouuan — APPROVED** [review]

**Comment by D4NZ-jpg** [comment]
@all-contributors please add @D4NZ-jpg for translation

**Pull request merged**
