### PR TITLE
refactor: Use Modern way for connecting signals and slots

### PR DESCRIPTION
**Pull request by coder3101**
## Description
Use Lambda or Pointer to member function syntax for connecting signals and slots. Get rid of `SIGNAL` and `SLOT` macros. SIGNAL and SLOT macros were used in Qt Prior to introduction to member function pointers.

## Motivation and Context
- Errors could be easily caught at compile time.
- Flexibility and Uniformity across the code
- Modernize the codebase
- No MOCs

## How Has This Been Tested?
Arch

## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [x] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by coder3101** [comment]
This is completed everywhere except for `Core`.

**Comment by ouuan** [comment]
Now I don't have a computer and can't test. Since MOC is not needed, can we remove it in CMakeLists.txt?

**Comment by coder3101** [comment]
> Now I don't have a computer and can't test. Since MOC is not needed, can we remove it in CMakeLists.txt?

I can test now but I think, keywords like `slot` , `emit`, `signal` keywords require MOC steps.

**Review by ouuan — APPROVED** [review]
It seems that we do need "set(CMAKE_AUTOMOC ON)".

**Pull request merged**
