### PR TITLE
Add linting by language server

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Add linting by language server.

## Related Issue

#156

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [x] New feature (changes which add functionality)
- [ ] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [ ] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [ ] The settings file in the old version can be used in the new version after this change.
- [ ] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [ ] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [ ] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [ ] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ouuan** [comment]
Both https://github.com/cpeditor/lsp-cpp/commit/4843650cb87d98266de9e326c5287f48f8e7bb74 and https://github.com/cpeditor/lsp-cpp/commit/24dc3eda5dc92cf4a54a19bdcd67c71ec11b9038 have error on my device, but https://github.com/cpeditor/lsp-cpp/commit/7f3fb8ebdaf6dbdc47c0c39942fbe21be2e6a3fe works well.

**Comment by coder3101** [comment]
If we write to a process stdin that is not running you will see a lot of output in stdout of cpeditor warning you about it. 

So I added that check to see if process is running only then we write to it's stdin. But as you pointed out the write has to be done in a sequence (initialize->open->change->close->close->shutdown->exit), From the client side we make sure that functions are called in this sequence and incase process was not running while initialize was written we buffer it, next time when we write open and see if something is in the buffer (in this case initialize) it has to be written before open is written. Also when process terminates the buffer must be cleared so that a new process may not get buffered input of last process. 

It is these cases that maybe causing the issue, but I will investigate it.

**Comment by coder3101** [comment]
> 
> 
> Both [cpeditor/lsp-cpp@4843650](https://github.com/cpeditor/lsp-cpp/commit/4843650cb87d98266de9e326c5287f48f8e7bb74) and [cpeditor/lsp-cpp@24dc3ed](https://github.com/cpeditor/lsp-cpp/commit/24dc3eda5dc92cf4a54a19bdcd67c71ec11b9038) have error on my device, but [cpeditor/lsp-cpp@7f3fb8e](https://github.com/cpeditor/lsp-cpp/commit/7f3fb8ebdaf6dbdc47c0c39942fbe21be2e6a3fe) works well.

So what exactly is the error LSP returns? It could help me narrow the scope for fixing the bug,

**Comment by ouuan** [comment]
When enabling linting, I got `[LSP Process Write Error]`.

When I start CP Editor with linting already on, I got `[Language server sent an error. Please check log for details.]`.

And here's a part of the log:

```
I[18:44:34.321] Updating file /tmp/CP Editor-BECkyD/sol.cpp with command clangd fallback
[/tmp/CP Editor-BECkyD]
/usr/bin/clang /tmp/CP Editor-BECkyD/sol.cpp -fsyntax-only -resource-dir=/usr/lib/clang/10.0.0
I[18:44:34.321] Failed to find compilation database for /tmp/CP Editor-BECkyD/sol.cpp
I[18:44:34.321] Updating file /tmp/CP Editor-BECkyD/sol.cpp with command clangd fallback
[/tmp/CP Editor-BECkyD]
/usr/bin/clang /tmp/CP Editor-BECkyD/sol.cpp -fsyntax-only -resource-dir=/usr/lib/clang/10.0.0
```

**Comment by coder3101** [comment]
> When I start CP Editor with linting already on, I got `[Language server sent an error. Please check log for details.]`.

When this error is logged, in log file a Error JSON is logged which contains what went wrong with Languages Server. Could you please also provide the Error JSON?

**Comment by ouuan** [comment]
```
ERR is 
{
    "code": -32600,
    "message": "server already initialized"
}
```

**Comment by ouuan** [comment]
> When I start CP Editor with linting already on, I got `[Language server sent an error. Please check log for details.]`.

I can fix this by adding a flag and only initialize the server once.

> When enabling linting, I got `[LSP Process Write Error]`.

I still get this error, with `E[19:29:18.336] Trying to remove file from TUScheduler that is not tracked: /tmp/CP Editor-tzcXiy/sol.cpp` in stderr.

**Comment by coder3101** [comment]
I will investigate this issue on Linux, since on Windows this works fine.

**Comment by coder3101** [comment]
I have found that it crashes on Linux with I/O error Transport error. I will work on this from tomorrow morning. (After 10 hours).

**Comment by coder3101** [comment]
@ouuan Please check if it still fails on your machine. I was able to run in both Windows and Linux.

**Comment by ouuan** [comment]
It works on my machine now.

**Comment by ouuan** [comment]
Now it sometimes crashes, I'll try to find the minimal way to reproduce it.

**Comment by ouuan** [comment]
This crashes on my machine:

1. Enable Python linting.
2. Open a Python tab.
3. Close the Python tab.
4. Disable Python linting.

Here are the last few lines in the log file:

```
[2020-04-24T20:08:29.299][INFO ][  onLSPServerResponseArrived  ][ LanguageServer.cpp ](263)::Response from Server has arrived
[2020-04-24T20:08:30.454][INFO ][           closeTab           ][   appwindow.cpp    ](344)::<index>: [1], 
[2020-04-24T20:08:30.454][INFO ][         closeConfirm         ][   mainwindow.cpp   ](885)::Confirming to close this window
[2020-04-24T20:08:30.454][INFO ][         closeConfirm         ][   mainwindow.cpp   ](899)::<confirmed>: [true], 
[2020-04-24T20:08:30.455][INFO ][         onTabChanged         ][   appwindow.cpp    ](777)::<index>: [0], 
[2020-04-24T20:08:30.456][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [View Mode], <value.toString()>: [split], 
[2020-04-24T20:08:30.456][INFO ][on_actionSplit_Mode_triggered ][   appwindow.cpp    ](1202)::Entered split mode
[2020-04-24T20:08:30.456][INFO ][on_actionSplit_Mode_triggered ][   appwindow.cpp    ](1205)::Restored splitter state
[2020-04-24T20:08:30.457][INFO ][       saveEditorStatus       ][   appwindow.cpp    ](505)::Save Editor status and load From File <loadFromFile>: [true], 
[2020-04-24T20:08:30.457][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [Hot Exit/Tab Count], <value.toString()>: [0], 
[2020-04-24T20:08:30.457][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [Hot Exit/Current Index], <value.toString()>: [-1], 
[2020-04-24T20:08:30.458][INFO ][        killProcesses         ][   mainwindow.cpp   ](639)::Killing all processes
[2020-04-24T20:08:30.469][INFO ][           ~Checker           ][    Checker.cpp     ](48)::Destroyed checker of type 0
[2020-04-24T20:08:31.320][INFO ][ on_actionSettings_triggered  ][   appwindow.cpp    ](728)::Launching settings window
[2020-04-24T20:08:33.550][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [LSP/Use Linting Python], <value.toString()>: [false], 
[2020-04-24T20:08:33.550][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [LSP/Delay Python], <value.toString()>: [2000], 
[2020-04-24T20:08:33.550][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [LSP/Path Python], <value.toString()>: [python], 
[2020-04-24T20:08:33.550][INFO ][             set              ][SettingsManager.cpp ](163)::<key>: [LSP/Args Python], <value.toString()>: [-m pyls], 
[2020-04-24T20:08:33.551][INFO ][      onSettingsApplied       ][   appwindow.cpp    ](960)::Apply settings for <pagePath>: [Extensions/Language Server/Python Server], 
[2020-04-24T20:08:33.551][INFO ][        applySettings         ][   mainwindow.cpp   ](452)::<pagePath>: [Extensions/Language Server/Python Server], <shouldPerformDigonistic>: [true], 
[2020-04-24T20:08:33.567][ERROR][   onLSPServerProcessError    ][ LanguageServer.cpp ](287)::LSP Process errored out <error>: [1], 
[2020-04-24T20:08:33.567][INFO ][             warn             ][ MessageLogger.cpp  ](65)::MessageLogger Warning <head>: [Language Server [python]], <body>: [Process was abruptly killed], 
```

**Comment by coder3101** [comment]
> This crashes on my machine:
> 
>     1. Enable Python linting.
> 
>     2. Open a Python tab.
> 
>     3. Close the Python tab.
> 
>     4. Disable Python linting.

I was able to reproduce this. Will push a fix now.

**Comment by coder3101** [comment]
Test this extensively and I insist @neko-para to also test it.

**Comment by ouuan** [comment]
Is there any reason to use `std::string` instead of `QString`?

**Comment by coder3101** [comment]
@ouuan Yes, lsp-cpp used std::string also Nlohmann JSON works only with std type. We can get rid of them all but aa complete LSP will have to be re-written which is not a good idea.

**Comment by ouuan** [comment]
Maybe we can use `QString` in other places except for `LSPProtocol.hpp` and `LSPUri.hpp`? BTW, LSP is "Language Server Protocol", so "LSPProtocol" doesn't make sense.

**Comment by coder3101** [comment]
> Maybe we can use `QString` in other places except for `LSPProtocol.hpp` and `LSPUri.hpp`?

I have used QString at all possible places in `LSPClient` if you think there are some more places where it could be of benefit. Please bring those changes.

**Comment by coder3101** [comment]
I just tested it with macOS and it seems to work nicely there as well.

**Comment by ouuan** [comment]
> I have used QString at all possible places in `LSPClient`

Then it's OK.

**Comment by ouuan** [comment]
Is it better to send messages of both the start and termination of the language server, or neither of them? I think it's OK to send messages of neither of them.

**Comment by ouuan** [comment]
I think it's time to merge this :thinking:

**Comment by coder3101** [comment]
If current minor release does not have any feature-adding PR already merged, merge it otherwise we can wait for next release cycle.

**Comment by ouuan** [comment]
> If current minor release does not have any feature-adding PR already merged, merge it otherwise we can wait for next release cycle.

Why? To make it more stable? In fact, including more features in a release makes the stable version more stable. Fewer features in a release means a higher frequency of making releases, thus the time for the users to test the beta release is shorter. The time needed to test (here "test" means to test in daily use instead of test intentionally) 10 features is the same as to test a single feature, so a shorter time to test leads to less stability.

However:

1. Fewer features in a release makes the beta version more stable. But we should focus on making the stable version more stable.
2. It is more stable if we include fewer features in a release with the same frequency of making releases. Do you like that?

**Comment by coder3101** [comment]
@ouuan I think it is better to merge it as you say, for I will start to work on auto complete and it will be better to put that to next release.

**Comment by ouuan** [comment]
> I think it is better to merge it as you say

Then you can approve this PR.

**Pull request merged**
