### PR TITLE
feat: Add localization for Chinese Traditional (Taiwan)

### PR DESCRIPTION
**Pull request by toto6038**
## Description

Add translation of the application, and review is done by @oToToT and @jw910731.
Some strings that raise Qt Linguist warning are reviewed again and they are correct.

## How Has This Been Tested?

Tested on Kubuntu 21.04.
## Screenshots (if appropriate)
圖片
圖片
圖片
圖片
圖片

## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [x] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by toto6038** [comment]
@all-contributors please add @toto6038 for 🌍

**Comment by toto6038** [comment]
@all-contributors please add @toto6038 for Translation

**Comment by ouuan** [comment]
You can directly push to the main repository, and it's recommended to do so.

**Comment by ouuan** [comment]
If you want others to collaborate, I can invite them to @cpeditor.

**Comment by toto6038** [comment]
> 
> 
> If you want others to collaborate, I can invite them to @cpeditor.

Currently no, but will contact you as needed.

**Pull request merged**
