### PR TITLE
Merge 6.6.2

### LINKED ISSUE #517: Crashes when opening the diff viewer
**Describe the bug**

The editor crashes when opening the diff viewer.

**To Reproduce**

Open the diff viewer.

**Environment**

 - OS: Arch Linux and Windows
 - CP Editor Version: Since #491

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Fix diff viewer crashes when output is empty.

It's the diff_match_patch that crashes. It crashes when an argument of diff_main is a null QString. The solution is to convert null QStrings to empty but not null QStrings.

## Related Issue

This fixes #517.

## How Has This Been Tested?

On Arch Linux.

## Checklist

- [ ] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ouuan** [comment]
It's not convenient to write the changelog before #513 is merged.

**Comment by coder3101** [comment]
I think the requirement for 2 Approving review for all PR is not a good idea. We can all agree to this rule.

- 1 Approving review required
- If a contributor has requested a review from themselves, the PR should not be merged without their approval.
- If PR author has requested reviews from `n` contributors. All must approve them before a merge.
- PR author should request review from each contributor that is most familiar with the codebase PR changes. 

If contributor doesn't reviews/replies in 48 hours. PR should proceed without his approval.

**Comment by ouuan** [comment]
> I think the requirement for 2 Approving review for all PR is not a good idea.

OK, as we can revert/fix after a PR is merged.

>  If a contributor has requested a review from themselves, the PR should not be merged without their approval.

I think the draft PR is the correct way to do this.

>  If PR author has requested reviews from `n` contributors. All must approve them before a merge.

I usually want anyone of the reviewers I requested to review :thinking:

**Comment by ouuan** [comment]
I think a better solution is to treat an approval from an admin/"code owner"(a feature of GitHub) as two approvals. But GitHub doesn't support this.

**Comment by ouuan** [comment]
However, we can require 2 approvals when we have more contributors/maintainers.

**Comment by coder3101** [comment]
> > I think the requirement for 2 Approving review for all PR is not a good idea.
> 
> OK, as we can revert/fix after a PR is merged.

Exactly

> 
> >  If a contributor has requested a review from themselves, the PR should not be merged without their approval.
> 
> I think the draft PR is the correct way to do this.

If I request my review on someone's PR(could be Draft), I must review before it's merged. Usually a review request from contributor to himself can signify, "This PR must have my approval". How does draft PR solves this?

> 
> >  If PR author has requested reviews from `n` contributors. All must approve them before a merge.
> 
> I usually want anyone of the reviewers I requested to review :thinking:
> 

That's fine for now, as list of reviewers grow. We should only request review from relevant contributors for PR. Like why request review from translator if no translations changed in PR? Likewise, for changes in `Settings` neko's review is important than mine.

**Comment by ouuan** [comment]
> If I request my review on someone's PR(could be Draft), I must review before it's merged. Usually a review request from contributor to himself can signify, "This PR must have my approval". How does draft PR solves this?

You said "contributor", I thought that means the one who opens the PR and write most codes. If you mean "reviewer", then your opinion is OK.

**Pull request merged**
