### PR TITLE
add script to build a fake DEB

### PR DESCRIPTION
**Pull request by neko-para**

### CODE REVIEW

**Comment by ouuan** [comment]
No explanation for this? Why add it?

**Comment by neko-para** [comment]
In #858 we adds a new requirement (libyaml-cpp), and I've noticed that there's not script to build the deb. (Other releases as well)
So I copy the commands from release.yaml to this script with some adjustment, and upload it in case it would be used in the future.

**Comment by ouuan** [comment]
If we have to add a script, why not reuse it in the workflow? But do we really need this script :thinking:? We can add a workflow to test DEB build, or trigger a test build in a fork.

**Comment by neko-para** [comment]
Then I will remove that.

**Pull request closed without merging**
