### PR TITLE
Associate files

### LINKED ISSUE #855: Associate source files to open in cpeditor
#846 and #849 only do this for macOS, I think we should do it for all OSs.

### PR DESCRIPTION
**Pull request by swift-zym**
## Description

Windows: Edit registry when first setup. 

Linux: Update desktop file.
## Related Issues / Pull Requests

Closes #855 
## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [ ] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by swift-zym** [comment]
This haven't been test on Linux.

**Comment by ouuan** [comment]
I think it would be better if the registry is modified in [Inno Setup](https://github.com/cpeditor/cpeditor/blob/master/dist/win/win-setup.iss) :thinking:

**Comment by ouuan** [comment]
BTW, next time you can create the new branch in the main repo instead of your fork.

**Comment by swift-zym** [comment]
> I think it would be better if the registry is modified in [Inno Setup](https://github.com/cpeditor/cpeditor/blob/master/dist/win/win-setup.iss) 🤔

But there is a portable version cpeditor , will that work?

**Comment by ouuan** [comment]
> But there is a portable version cpeditor , will that work?

Why don't you install if you want your registry to be modified :thinking:

**Comment by swift-zym** [comment]
OK, I’ll create a new PR.

**Pull request closed without merging**
