### PR TITLE
ci(snap): fix version and update README

### PR DESCRIPTION
**Pull request by coder3101**

### CODE REVIEW

**Comment by ouuan** [comment]
The "Get it from" is invisible with a height of 28px. Do we need that line?

**Comment by coder3101** [comment]
> The "Get it from" is invisible with a height of 28px. Do we need that line?

Not necessary but why do we keep it along with downloads, sponsors and other badges. I suggest we put it in a new line below others, it is visible and centered to draw focus of users.

**Comment by coder3101** [comment]
Something like this:
Screenshot from 2021-07-15 09-51-07

**Comment by ouuan** [comment]
Yeah, but I'm wondering why we should draw attention to it. The badge somehow sounds like "you need to get it from snap store", but actually the snap installation method is targeted at only a few users.

**Comment by coder3101** [comment]
We set the `width=15%` and use the second row in README for listing badges with store presence. 
Screenshot from 2021-07-15 10-42-45

**Comment by ouuan** [comment]
I think the badges in the version table are enough.

**Comment by coder3101** [comment]
> I think the badges in the version table are enough.

Fine, remove the "Get it from Snap store" badge and approve.

**Review by ouuan — APPROVED** [review]

**Review by neko-para — APPROVED** [review]

**Comment by ouuan** [comment]
I reverted the "fix version" part by mistake...

**Comment by ouuan** [comment]
> I reverted the "fix version" part by mistake...

However, it's a good example that we should do one thing per commit.

**Pull request merged**
