### PR TITLE
New preferences window and settings system

### LINKED ISSUE #166: New preference window with scrollable tabs on the left
**Is your feature request related to a problem? Please describe.**

The current preference window is not able to contain too many options.

**Describe the solution you'd like**

Use a preference window with scrollable tabs on the left. i.e. Make tabs be QPushButtons in a QScrollArea on the left.

And users should be able to search for options.

**Describe alternatives you've considered**

Make the default size of the preference window bigger, so more tabs can be placed in it without the left and right buttons.

**Additional context**

N/A

### LINKED ISSUE #189: Add warning when switching between snippets
**Is your feature request related to a problem? Please describe.**

You won't get any warnings if you close the preference window without saving the settings. What's worse, since the "OK" and "Apply" buttons don't save the snippets, it's very likely that the user forgets to save the snippets and lose them. 

**Describe the solution you'd like**

Add warning when closing the preference window with settings unsaved, and other operations like changing the snippet name/language, which may lose the snippets.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### LINKED ISSUE #202: Set output limit, and make message length limit, HTML diff viewer length limit and open file length limit customizable
**Is your feature request related to a problem? Please describe.**

Now the application (maybe the whole system) will hang up when the output is too big.

And users can't set a suitable limit for messages, HTML diff viewer length limit  and code length limit on their device.

**Describe the solution you'd like**

Set customizable length limits for output, message, HTML diff viewer and codes.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Use a completely new preferences window with settings well-organized. It's very extendable. Users are warned when leaving a page with settings modified. You can search for settings. It's mainly inspired by the [KDE systemsettings](https://github.com/KDE/systemsettings).

This PR contains the [first step](https://github.com/cpeditor/cpeditor/issues/166#issuecomment-605607699) of the new preferences window.

## Related Issue

This resolves #166, resolves #189, resolves #202.

## Motivation and Context

There are more and more settings, but the old preference window is not very extendable.

## How Has This Been Tested?

It's still developing.

## Screenshots (if appropriate)

(These are WIP screenshots on Manjaro KDE)

image

image

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [x] New feature (changes which add functionality)
- [ ] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [x] The settings file in the old version can be used in the new version after this change.
- [ ] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [ ] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by coder3101** [comment]
I would suggest one of you to squash commits and force push. I see a lot work is still to be done here and it already has 52 commits which makes this page big to scroll down. You should force push after a `git rebase -i HEAD~52` and squash every irrelevant commit into some other commit.

**Comment by ouuan** [comment]
> I would suggest one of you to squash commits and force push. I see a lot work is still to be done here and it already has 52 commits which makes this page big to scroll down. You should force push after a `git rebase -i HEAD~52` and squash every irrelevant commit into some other commit.

These are meaningful commits, only commits like `test 1`, `test 2`, `test 3` should be squashed, otherwise it will be hard to find a specific change.

**Comment by coder3101** [comment]
@ouuan As I mentioned *irrelevant commits* (that which you don't care to look back again in future for changes)

**Comment by ouuan** [comment]
(I'm trying to trigger the Pull Assistant.)

**Comment by ouuan** [comment]
I think only the formatting commit should be squashed :thinking:

**Comment by ouuan** [comment]
> I think only the formatting commits should be squashed

Finished.

**Comment by ouuan** [comment]
@coder3101 If you think other commits should be squashed as well, please point out which commits.

**Comment by coder3101** [comment]
I am working on LSP from master and would like to know that should I add LSP options in the current preference window or just keep in in SettingsManager and you include it directly in this Window?

These new Settings should be added. In a section named "Language Server Protocol"

```cpp
	// Settings related to LSP
    static void setUseLSP(bool); // Turn on or off Language server protocol
    static bool isUseLSP();

    static void setReportDiagonistics(bool); // If LSP is on should we report error and warnings on fly in editor?
    static bool isReportDiagonistics();

    static void setLSPAutoComplete(bool); // If LSP is on should we provide autocomplete from LSP?
    static bool isLSPAutoComplete();

    static void SettingsManager::setLSPPath(QString); // Path to LSP executable or name if it is in PATH
    static QString SettingsManager::getLSPPath();
    static void SettingsManager::setLSPRuntimeArguments(QStringList);
    static QStringList SettingsManager::getLSPRuntimeArguments();
```

**Comment by ouuan** [comment]
> I am working on LSP from master and would like to know that should I add LSP options in the current preference window or just keep in in SettingsManager and you include it directly in this Window?

The new preferences window is nearly finished, we'll merge it into master soon. You can wait until it's merged into master and open a new branch based on the new master and work on LSP on the new branch. However, in the new preferences window, it's extremely easy to add new settings, so you don't need to worry about this.

**Comment by ouuan** [comment]
Now all features are added, we need to:

1. Review the codes.
2. Test in personal use.
3. Write documents.
4. Resolve conflicts and merge into master.

**Comment by coder3101** [comment]
Or how about I merge my lsp (cherry-pick) a commit to master now and when you have merged your branch to master, You can provide UI for those functions? This way, I can only focus on LSP and you can organize them as you want, it is because you have been working on Preferences as you said.

Otherwise, I will continue to work on my branch and rebase the things when you have merged your preference window to master.

**Comment by ouuan** [comment]
> Or how about I merge my lsp (cherry-pick) a commit to master now and when you have merged your branch to master, You can provide UI for those functions? This way, I can only focus on LSP and you can organize them as you want, it is because you have been working on Preferences as you said.
> 
> Otherwise, I will continue to work on my branch and rebase the things when you have merged your preference window to master.

Please don't merge LSP to master, I don't want to add LSP in v6.3. Please create a new branch for it, and work on that branch before all things are finished.

**Comment by coder3101** [comment]
> 
> 
> > Or how about I merge my lsp (cherry-pick) a commit to master now and when you have merged your branch to master, You can provide UI for those functions? This way, I can only focus on LSP and you can organize them as you want, it is because you have been working on Preferences as you said.
> > Otherwise, I will continue to work on my branch and rebase the things when you have merged your preference window to master.
> 
> Please don't merge LSP to master, I don't want to add LSP in v6.3. Please create a new branch for it, and work on that branch before all things are finished.

I checked this branch and it has so many new files and completely new structures, rebase will have
issues as well (CONFLICT). I have now decided to wait before this is merged, I will also help in testing it now.

**Comment by coder3101** [comment]
Adding to list below:

> Now all features are added, we need to:
> 
>     1. Review the codes.
> 
>     2. Test in personal use.
> 
>     3. Write documents.
> 
>     4. Resolve conflicts and merge into master.

5. Log Events to LOG File.

**Comment by ouuan** [comment]
I'd like to merge into master first and then make other changes.

**Pull request merged**
