### PR TITLE
docs(README): add demo GIF

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Add two GIFs in the README to attract new users.

These features are basic and is only a small part of CP Editor, but they are easy to display and attracts new users.

### CODE REVIEW

**Comment by coder3101** [comment]
I think it is best to have only one GIF and that too, on top just after the logo.

My review:
Basic usage GIF is great (I'll share a macOS themed GIF for the same)
Code fetching is too much. (In my opinion, Readme gif should focus only on basic UI and usage)

**Comment by ouuan** [comment]
> I think it is best to have only one GIF.

If only one GIF, I'd like two combine these two. i.e. parse a contest with a short div2 A and solve it. I think the Competitive Companion support is important. And I don't think having two GIFs is a problem.

> on top just after the logo

That's bad. We need the line with useful links at top.

**Comment by StudyingFather** [comment]
> I think it is best to have only one GIF and that too, on top just after the logo.
> 
> My review:
> Basic usage GIF is great (I'll share a macOS themed GIF for the same)
> Testcase fetching is too much. (In my opinion, Readme gif should focus only on basic UI and usage)

I think testcase fetching is a featured function, making CP Editor different from other editors. So it is necessary to show the function.

**Comment by coder3101** [comment]
I think an all round usage in one GIF makes more sense. 

1. Fetch testcase
2. Code solution
3. Compile/Run/Test
4. Submit to CF

> We need the line with useful links at top.

If you put above GIF, you don't need the lines. This GIF is only demonstration of usage.

**Comment by ouuan** [comment]
> If you put above GIF, you don't need the lines. This GIF is only demonstration of usage.

I don't understand.

**Comment by coder3101** [comment]
The GIF location looks good under PC. (last time I was browsing on mobile, and it looks like it was way below in README)

**Comment by coder3101** [comment]
ezgif com-gif-maker(1)

This GIF is good to put in the README.

**Review by coder3101 — DISMISSED** [review]

**Comment by coder3101** [comment]
@ouuan Either merge the PR if you liked the changes and approve of it, or commit changes to dismiss the review.

**Comment by ouuan** [comment]
The new GIF is too long. I'll add a new one about 6 days later.

**Comment by coder3101** [comment]
New GIF looks good, but why didn't you showed the problem parsing step. It would have been a complete demo then.

**Comment by ouuan** [comment]
> why didn't you showed the problem parsing step

It's simply too short. It lasts for only a few frames.

**Comment by ouuan** [comment]
We can make the parsing process longer by parsing a full contest.

**Comment by coder3101** [comment]
> We can make the parsing process longer by parsing a full contest.

I am looking for a tool that can speed only a section of GIF, so we can keep the normal speed for parsing then speed up for rest of the GIF.

**Comment by coder3101** [comment]
> > We can make the parsing process longer by parsing a full contest.
> 
> I am looking for a tool that can speed only a section of GIF, so we can keep the normal speed for parsing then speed up for rest of the GIF.

https://www.veed.io/tools/gif-speed-changer 

Split the GIF and speed one split and keep other split normal. Export the merged GIF

**Comment by ouuan** [comment]
Now the CF judgers are very slow. I had many failures for the current perfect GIF (no coding mistake, network is fine, etc.). Let's just take it.

**Review by coder3101 — APPROVED** [review]

**Pull request merged**
