### PR TITLE
fix(FontItem): Fix #260

### LINKED ISSUE #260: New Preference window loses focus after picking font in macOS
**Describe the bug**

After choosing the font from Font Picker the Preference window goes in the background (loses Focus) in macOS. This issue was with last preference window as well (#160) and fixed (8d44a1ad1fba0534746be6b4f78b3415aec0bbe9) if we add `raise()` just after user either has selected font or aborted the window.

**To Reproduce**

1. Open Editor
2. Open preferences
3. Change Font
4. The preference window will go in the background as soon as the font is picked. We cannot apply the changes as a result unless to switch to the preference window again.

**Screenshots**

Annotation 2020-04-26 134911

**Environment**

 - OS: macOS 10.15
 - CP Editor Version: [master and beta]

**Additional context**

`raise()` should be called as soon as font picker closes. It will have no effect on Linux and Windows, So no conditional for OS.

### PR DESCRIPTION
**Pull request by coder3101**
## Description
Fix #260 

## Type of changes

- [x] Bug fix (changes which fix an issue)
- [ ] New feature (changes which add functionality)
- [ ] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [ ] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [ ] The settings file in the old version can be used in the new version after this change.
- [ ] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [ ] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [ ] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ouuan** [comment]
Should we make a release now or wait until the next version?

**Comment by coder3101** [comment]
We can wait. It is not that big of a problem. User can switch to background and bring back the Preference window. Plus is only affects the beta users.

**Comment by coder3101** [comment]
Tested and works fine on my iMAC

**Comment by ouuan** [comment]
Did you cherry-pick it?

**Comment by ouuan** [comment]
I think it's better to merge from v6.3. However, it's also OK to cherry-pick since it won't cause any conflict :thinking:

**Comment by coder3101** [comment]
> Did you cherry-pick it?

Yes

**Comment by coder3101** [comment]
I do still see that v6.3 is showing 1 commit ahead of master. I will create a PR from v6.3 for master and merge it now. Seems that cherry-pick is counted as another different commit.

**Comment by coder3101** [comment]
> I think it's better to merge from v6.3

From next time we will do this only. Because conflict has low chances especially for hotfixes.

**Pull request merged**
