### PR TITLE
chore: delete doc

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Delete the doc directory.

### CODE REVIEW

**Comment by coder3101** [comment]
Shouldn't the translated stuff be re-used in website before deleting them?

**Comment by ouuan** [comment]
> Shouldn't the translated stuff be re-used in website before deleting them?

We are using git.

**Comment by ouuan** [comment]
Do you mean we should show users with the old but translated version?

**Comment by coder3101** [comment]
@ouuan Yes.

**Comment by ouuan** [comment]
How? Where? I don't think it's a good idea to use the old version in the links for documentation.

**Comment by ouuan** [comment]
I think we can either show users the English version, or wait until the translation is finished.

**Comment by coder3101** [comment]
At least you can setup the Russian and Chinese version in docs on website and use these translation and then delete them here. For docs that are not yet translated you can keep the same English content and possibly add a warning "WIP" 

It will help other translators to just translate things instead of worrying about setup.

**Comment by coder3101** [comment]
Okay

**Review by coder3101 — APPROVED** [review]

**Pull request merged**
