### PR TITLE
docs: use YAML issue forms

### PR DESCRIPTION
**Pull request by ouuan**
## Description

Use [YAML issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/).

## Previews

https://github.com/cpeditor/cpeditor/blob/issue-form/.github/ISSUE_TEMPLATE/bug_report.yaml

https://github.com/cpeditor/cpeditor/blob/issue-form/.github/ISSUE_TEMPLATE/feature_request.yaml

### CODE REVIEW

**Comment by ouuan** [comment]
About the "Are you willing to contribute to this?" section:

As a maintainer, I'm usually willing to contribute to an issue but not at present. However, normal contributors usually contribute right now or never. So I think it's fine to only have the current three options, and maintainers can simply check none of them. Or should we have an option to "contribute in the future / not at present"?

**Comment by ouuan** [comment]
> neko-para reacted with thumbs up emoji

It's confusing to upvote an alternative-question :new_moon_with_face:

**Comment by neko-para** [comment]
> > neko-para reacted with thumbs up emoji
> 
> It's confusing to upvote an alternative-question 🌚

I Just mean it sounds good

**Comment by ouuan** [comment]
> I Just mean it sounds good

But there are two options. Which one sounds good?

**Comment by neko-para** [comment]
🤔

**Review by coder3101 — DISMISSED** [review]

**Review by neko-para — APPROVED** [review]

**Review by coder3101 — APPROVED** [review]

**Pull request merged**
