### PR TITLE
doc(SETTING_HELP): add setting help

### PR DESCRIPTION
**Pull request by neko-para**
add document about the new settings system in Chinese
fix the wrong title of src/Settings/README.md

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [ ] New feature (changes which add functionality)
- [x] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by neko-para** [comment]
Actually I tried to write it in English, but it's too hard for me.

**Comment by coder3101** [comment]
@ouuan You should translate this into English. Why do we need chinese readme?

**Comment by ouuan** [comment]
> Why do we need chinese readme?

What do you mean by "readme"? The README.md at the root is very useful. The document in this PR is not necessary, but not bad as well.

**Comment by coder3101** [comment]
@ouuan By readme at this context I meant the readme affected in the PR? I know the root Readme.md and it's importance.

**Comment by ouuan** [comment]
> the readme affected in the PR

What's that? The typo Extensions->Settings? I can't find Chinese "readme" in this PR.

**Comment by neko-para** [comment]
There should be an English version, but I'm not good at it. So I write a Chinese version and hope someone could help me.

**Comment by coder3101** [comment]
@neko-para and @sadykhzadeh Please open a new PR where you translate all the things that I have commented https://github.com/cpeditor/cpeditor/commit/e97f864faf435c2777374eb801091674ad062a4f for you here.

**Comment by sadykhzadeh** [comment]
> @sadykhzadeh Please open a new PR where you translate all the things that I have commented [e97f864](https://github.com/cpeditor/cpeditor/commit/e97f864faf435c2777374eb801091674ad062a4f) for you here.

Well. I'll start translating as soon as I can.

**Comment by coder3101** [comment]
After a discussion with @ouuan. We have reached to conclusion that we will have separate `README_xx-XX` for each language inside different sub directories. I have already created empty README files with suffix of language and @neko-para and @sadykhzadeh should open a PR with translation from `README.md`.

@ouuan Please do mention any important thing in the `Settings/README.md` before they propose the PR. In this PR neko mentioned some more things (in his translations) that I have not included in `Settings/README.md` because I did not understood them.

**Pull request closed without merging**
