### PR TITLE
Migrate to Qt 5.15.0

### LINKED ISSUE #374: Migrate to Qt 5.15
Qt 5.15 has just been released today, and I've roughly read the [new features](https://wiki.qt.io/New_Features_in_Qt_5.15) and the [changelog](https://wiki.qt.io/Qt_5.15.0_Change_Files) and found these new features/changes useful/notable for us, and we can migrate to it some time later (like when it's available on Arch Linux and Ubuntu PPA).

-   >  The binary JSON representation is deprecated. The CBOR format should be used instead.

    It seems that there's no function like `QJsonDocument::toCbor`, and in order to use the CBOR format, we may need to use QCborValue (I'm not very sure). However, since it's not necessary to use a compacted format, we can simply use `toJson` and `fromJson` instead of `toBinary` and `fromBinary`.

-   > QProcess:
    > - Overloads of start/execute/startDatached that parse a single command string into program and arguments have been marked as deprecated. A static helper splitCommand has been added to construct a QStringList from a command string.

    We should use `splitCommand` with the `program, arguments` version of `start`. With `splitCommand`, we can also avoid manually adding quotes to paths, and `Util::splitArgument` can be replaced by it, too.

-   > Added static template QDebug::toString function, which streams the given object into a QDebug instance that operates on a string, and then returns that string.

    It's strange that I didn't find `QDebug::toString` in [the documentation](https://doc.qt.io/qt-5.15/qdebug.html). However, if there's such a function, we can use it in the EventLogger. In fact, we can manually implement something like `QDebug::toString` easily, but I just came up with this idea when I saw this new feature in Qt 5.15.

### PR DESCRIPTION
**Pull request by coder3101**
### You can add new topics to this checklist.
Checklist for Migration
- [x] Remove deprecated stream formatters
- [x] `QProcess::start(program, argsList)` instead of `QProcess::start()`.
- [x] `toJSON` and `fromJSON` instead of `toBinary` and `fromBinary` in QJsonDocument. (COBR instead of Binary or get rid of binary completely)
- [x] CI should use Qt 5.15.0 on all operating systems.
- [x] Change AUR files and requirements.
- [x] Optionally mention in changelog the migration.
- [ ] Wait until [the PPA on Ubuntu](https://launchpad.net/~beineri) has 5.15.0.

### After merge

- [ ] Add CI Test in the branch protection rules.

## Related Issue

This closes #374.

## Motivation and Context

1. There are some new features that are useful.
2. For Arch Linux users who install from AUR, there will be tons of deprecated warnings when compiling if we don't migrate to Qt 5.15.

## Type of changes

- [x] Documentation (changes which modify the documentation only)
- [x] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [x] Build (Changes that affect the build system or external dependencies)
- [x] CI (changes to CI configuration files and scripts)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

### CODE REVIEW

**Comment by ouuan** [comment]
Now all deprecated warnings are resolved.

**Comment by ouuan** [comment]
> Yes, we should merge this now and wait for 5.15 PPA, if it takes more than 3 weeks, we can still release 6.6 but not put in changelog the migration. This is because no matter what API we use locally, there is nothing special functionality of Qt 5.15 that we are using; Migration is incomplete without Qt 5.15 DLL/shared Libraries being bundled in EXE/AppImage/DMG.

We are using `QProcess::splitCommand`.

**Comment by ouuan** [comment]
We may also need to wait for Manjaro to add Qt 5.15 in the stable branch :thinking: Now it's only in the testing branch.

**Comment by coder3101** [comment]
> 
> 
> We may also need to wait for Manjaro to add Qt 5.15 in the stable branch 🤔 Now it's only in the testing branch.

We will only wait for Manjaro, It is usually 2-3 weeks behind Arch Linux. So, it should be coming up soon. As long as our CI can build this branch, I think we can release the next versions with Install assets even after this PR has been merged. Conditional check for Qt version can be used to help code compile on 5.14. When PPA is available and we have updated our CI, We can optionally remove the Qt Version checks and put in the changelog and build docs that "We have migrated"

**Comment by ouuan** [comment]
qt5-base 5.15.0 has been in the stable branch of Manjaro since 2 days ago.

**Pull request merged**
